[package]
name = "whir"
description="fully self-contained speed test ('cargo install whir' then run 'whir')"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
